# ============================================================
# program.tcl
#
# Program FPGA via JTAG
#
# Run from:
#   AXI_FIFO_Modulator/scripts/
#
# ============================================================

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

set SCRIPT_DIR [file normalize [file dirname [info script]]]
set ROOT_DIR   [file normalize "$SCRIPT_DIR/.."]

set PROJECT_DIR  "$ROOT_DIR/project"
set PROJECT_NAME "DF5_project"

# Bitstream generated by Vivado implementation
set BIT_FILE "$PROJECT_DIR/$PROJECT_NAME.runs/impl_1/design_1_wrapper.bit"

# ------------------------------------------------------------
# Check bitstream
# ------------------------------------------------------------

puts ""
puts "=========================================="
puts "FPGA Programming"
puts "=========================================="
puts ""

if {![file exists $BIT_FILE]} {
    puts "ERROR: Bitstream does not exist:"
    puts "       $BIT_FILE"
    puts ""
    puts "Run 'make build' first."
    exit 1
}

puts "Bitstream:"
puts "  $BIT_FILE"
puts ""

# ------------------------------------------------------------
# Open Hardware Manager
# ------------------------------------------------------------

puts "Opening Hardware Manager..."

open_hw_manager

# ------------------------------------------------------------
# Connect to hw_server
# ------------------------------------------------------------

puts "Connecting to hw_server..."

connect_hw_server

# ------------------------------------------------------------
# Open JTAG target
# ------------------------------------------------------------

puts "Opening JTAG target..."

open_hw_target

# ------------------------------------------------------------
# Find FPGA
# ------------------------------------------------------------

set devices [get_hw_devices]

if {[llength $devices] == 0} {
    puts "ERROR: No JTAG devices found."
    puts ""
    puts "Check:"
    puts "  - FPGA board is connected"
    puts "  - JTAG cable is connected"
    puts "  - hw_server is running"
    exit 1
}

puts ""
puts "Detected JTAG devices:"

foreach device $devices {
    puts "  $device"
}

puts ""

# ------------------------------------------------------------
# Find XC7A35T
# ------------------------------------------------------------

set fpga ""

foreach device $devices {
    set part_name [get_property PART $device]

    puts "Device: $device"
    puts "Part:   $part_name"

    if {[string match "*xc7a35t*" [string tolower $part_name]]} {
        set fpga $device
    }
}

if {$fpga eq ""} {
    puts "ERROR: XC7A35T FPGA was not found."
    exit 1
}

puts ""
puts "Selected FPGA:"
puts "  $fpga"
puts ""

# ------------------------------------------------------------
# Program FPGA
# ------------------------------------------------------------

puts "Programming FPGA..."

set_property PROGRAM.FILE $BIT_FILE $fpga

program_hw_devices $fpga

# ------------------------------------------------------------
# Refresh device
# ------------------------------------------------------------

puts ""
puts "Refreshing device..."

refresh_hw_device $fpga

# ------------------------------------------------------------
# Done
# ------------------------------------------------------------

puts ""
puts "=========================================="
puts "FPGA programmed successfully"
puts "=========================================="
puts ""

# ------------------------------------------------------------
# Close
# ------------------------------------------------------------

close_hw_target
disconnect_hw_server
close_hw_manager

exit 0